openapi: 3.0.0
info:
  description: Hecate Open API
  version: 1.0.0
  title: Hecate
servers:
  - url: 'https://bo.hec.dev-dropteam.com'
  - url: 'http://0.0.0.0:4010'
  - url: 'https://hecate.ppr-aws2.hermes.com'
  - url: 'https://finance-admin-v2.aws3.hermes.com'
paths:
  /footer:
    get:
      tags:
        - "Footer"
      summary: Get Footer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/footer"
components:
  schemas:
    footer:
      description: Footer
      properties:
        id:
          type: string
          x-faker: random.uuid
        newsletter:
          type: object
          $ref: "#/components/schemas/newsletter"
        menu:
          type: object
          $ref: "#/components/schemas/menu"
    newsletter:
      description: A page with product informations
      type: object
      properties:
        fr:
          description: newsletter vr FR
          type: object
          properties:
            title:
              type: string
              example: Abonnez-vous à l'actualité d'Hermès
            description:
              type: string
              example:
                Recevez les dernières actualités du Groupe en vous abonnant à
                nos publications.
            other:
              type: string
              x-faker: lorem.slug
              example: Formulaire à venir
        en:
          description: newsletter vr EN
          type: object
          properties:
            title:
              type: string
              example: Abonnez-vous à l'actualité d'Hermès
            description:
              type: string
              example:
                Recevez les dernières actualités du Groupe en vous abonnant à
                nos publications.
            other:
              type: string
              x-faker: lorem.slug
              example: Formulaire à venir
    menu:
      description: A page with product informations
      type: object
      properties:
        fr:
          description: newsletter vr FR
          type: array
          minimum: 2
          items:
            type: object
            properties:
              title:
                type: string
                x-faker: lorem.slug
                example: Sites du groupe
              items:
                type: array
                minimum: 2
                items:
                  properties:
                    label:
                      type: string
                      x-faker: lorem.slug
                      example: Opportunités d'emploi
                    url:
                      type: string
                      x-faker: lorem.slug
                      example: /
        en:
          description: newsletter vr FR
          type: array
          minimum: 2
          items:
            type: object
            properties:
              title:
                type: string
                x-faker: lorem.slug
                example: Sites du groupe
              items:
                type: array
                minimum: 2
                items:
                  properties:
                    label:
                      type: string
                      x-faker: lorem.slug
                      example: Opportunités d'emploi
                    url:
                      type: string
                      x-faker: lorem.slug
                      example: /
    categoryModel:
      description: categorie model
      type: object
      $ref: "#/components/schemas/obejectFiltre"
    obejectFiltre:
      properties:
        fr:
          description: category vr FR
          type: object
          properties:
            titleYears:
              type: string
              x-faker: lorem.slug
              example: Année
            titleDocumentType:
              type: string
              x-faker: lorem.slug
              example: Type de document
            titleEventType:
              type: string
              x-faker: lorem.slug
              example: Type d'événement
            items:
              type: array
              minimum: 2
              items:
                properties:
                  id:
                    type: integer
                    format: int32
                    example: 21ac639b-6378-4da8-8639-fb5b93a010df
                  years:
                    type: array
                    items:
                      type: string
                      x-faker: lorem.slug
                      example: 2018
                  documentType:
                    type: array
                    items:
                      type: string
                      x-faker: lorem.slug
                      example: Présentations
                  eventType:
                    type: array
                    items:
                      type: string
                      x-faker: lorem.slug
                      example: Communiqués de presse
                  name:
                    type: string
                    x-faker: lorem.slug
                    example: fr -The Shawshank Redemption
                  publicationDate:
                    type: string
                    format: date
                    example: 2018-06-29
                  publicationHour:
                    type: string
                    format: date-time
                    example: 11:30:00
                  documentWeight:
                    type: string
                    x-faker: lorem.slug
                    example: PDF
                  documentSize:
                    type: string
                    x-faker: lorem.slug
                    example: 31.Mo
                  version:
                    type: string
                    x-faker: lorem.slug
                    example: e-accessible
                  href:
                    type: string
                    x-faker: lorem.slug
                    example: >-
                      https://finance.hermes.com/var/finances/storage/original/application/fbeac18beab921bc4cd0d100b9f37113.pdf
                  title:
                    type: string
                    x-faker: lorem.slug
                    example: >-
                      Two imprisoned men bond over a number of years, finding
                      solace and eventual redemption through acts of common
                      decency.
        en:
          description: category vr FR
          type: object
          properties:
            titleYears:
              type: string
              x-faker: lorem.slug
              example: Année
            titleDocumentType:
              type: string
              x-faker: lorem.slug
              example: Type de document
            titleEventType:
              type: string
              x-faker: lorem.slug
              example: Type d'événement
            items:
              type: array
              minimum: 2
              items:
                properties:
                  id:
                    type: integer
                    format: int32
                    example: 21ac639b-6378-4da8-8639-fb5b93a010df
                  years:
                    type: array
                    items:
                      type: string
                      x-faker: lorem.slug
                      example: 2018
                  documentType:
                    type: array
                    items:
                      type: string
                      x-faker: lorem.slug
                      example: Présentations
                  eventType:
                    type: array
                    items:
                      type: string
                      x-faker: lorem.slug
                      example: Communiqués de presse
                  name:
                    type: string
                    x-faker: lorem.slug
                    example: fr -The Shawshank Redemption
                  publicationDate:
                    type: string
                    format: date
                    example: 2018-06-29
                  publicationHour:
                    type: string
                    format: date-time
                    example: 11:30:00
                  documentWeight:
                    type: string
                    x-faker: lorem.slug
                    example: PDF
                  documentSize:
                    type: string
                    x-faker: lorem.slug
                    example: 31.Mo
                  version:
                    type: string
                    x-faker: lorem.slug
                    example: e-accessible
                  href:
                    type: string
                    x-faker: lorem.slug
                    example: >-
                      https://finance.hermes.com/var/finances/storage/original/application/fbeac18beab921bc4cd0d100b9f37113.pdf
                  title:
                    type: string
                    x-faker: lorem.slug
                    example: >-
                      Two imprisoned men bond over a number of years, finding
                      solace and eventual redemption through acts of common
                      decency.
