<?php

/**
 * @file
 * Extend Term Reference Tree.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Hook_form_alter().
 */
function he_term_reference_tree_extend_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $document_form_ids = [
    'node_document_form',
    'node_document_edit_form',
  ];

  if (in_array($form_id, $document_form_ids)) {
    $form['#attached']['library'][] = 'he_term_reference_tree_extend/tree';
  }
}
