<?php

/**
 * @file
 * This is the module to alter node document form.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function he_doc_form_form_node_document_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $date = strtotime(date('Y-m-d 00:00:00'));
  $form['field_datetime_publication']['widget'][0]['value']['#default_value'] = DrupalDateTime::createFromTimestamp($date);
}
