openapi: 3.0.0
info:
  description: Hecate Open API
  version: 1.0.0
  title: hec-lambda
paths:
  /euronext/fr:
    get:
      tags:
        - "EuroNext"
      summary: Get stock market price for FR language
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: arn:aws:lambda:eu-west-1:594067985087:function:Hermes-hecate_euronext-fr
        httpMethod: GET
        type: aws