version: "2"

services:
  web:
    build: ./images/backoffice/

    ports:
      - "${PORT_WEB}:80"
        # Settings xdebug
    extra_hosts:
      - "docker_host:10.200.10.1"
    environment:
      - DOCUMENTROOT=${DOCUMENTROOT}
    volumes:
      - ${LOCALPATH_BACKOFFICE}:/var/www/html/:delegated
      - ./config/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./config/apache2/sites-enabled/:/etc/apache2/sites-enabled
      - ./config/php/hecate.ini:/usr/local/etc/php/conf.d/hecate.ini
    depends_on:
      - database
      - mailhog
    links:
      - database:mysql
      - mailhog
    tty: true
    env_file: .env

  # database container - dropteam images
  database:
    image: mysql:5.7
    ports:
      - "${PORT_DATABASE}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d/

  gatsby:
    build: ./images/gatsby/
    ports:
      - "81:80"
    volumes:
      - ${LOCALPATH_FRONTOFFICE}:/var/www/html/:delegated
    expose:
      - 80
    depends_on:
      - web
    links:
      - web
    tty: true

  # phpmyadmin container - dropteam images
  phpmyadmin:
    image: dropteam/docker-phpmyadmin
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_SIZE=${UPLOAD_SIZE}
    depends_on:
      - database
    links:
      - database:mysql

  # mailhog container - official images
  mailhog:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAILHOG2}:1025"
      - "${PORT_MAILHOG1}:8025"

  # Elastic search
  elasticsearch:
    image: elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"

    # Swagger UI
  swaggerui:
    image: swaggerapi/swagger-ui:v3.25.0
    ports:
      - "${PORT_SWAGGER}:8080"
    volumes:
      - ../iaac/swagger:/swagger:delegated
    environment:
      - SWAGGER_JSON=/swagger/openapi.yaml

    # Swagger Editor
  swaggereditor:
    image: swaggerapi/swagger-editor:v3.8.0
    ports:
      - "${PORT_SWAGGEREDITOR}:8080"
    volumes:
      - ../iaac/swagger:/swagger:delegated

  prism:
    image: stoplight/prism:3
    ports:
      - "${PORT_PRISM}:4010"
    environment:
      - NODE_ENV=development
    volumes:
      - ../iaac/swagger/:/tmp/
    command: ["mock", "-h", "0.0.0.0", "-d", "/tmp/openapi.yaml"]

  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "8001:8080"
    environment:
      - SERVICES=cloudfront,s3,edge
      - DEBUG=1
      #- DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DNS_LOCAL_NAME_PATTERNS='.*cloudfront\.net'
      - CLOUDFRONT_STATIC_PORTS= 1
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ../:/var/hecate:delegated
