<?php

/**
 * @file
 * This is the module to handle file size.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_node_presave().
 */
function he_file_size_node_presave(NodeInterface $node) {
  $bundle = $node->bundle();

  // Only for Node Pdf File.
  if ($bundle != 'pdf_file') {
    return;
  }

  if (!$node->hasField('field_file')) {
    return;
  }

  if (!$node->hasField('field_filesize')) {
    return;
  }

  // Get file size.
  $file = $node->field_file->entity;
  $filesize = $file->get('filesize')->getString();

  // Format file size.
  $language = $node->language()->getId();
  $formated_filesize = format_size($filesize, $language);

  // Set file size.
  $node->set('field_filesize', $formated_filesize);

  // Logs a notice.
  Drupal::logger('he_file_size')->notice('La taille du fichier ' . $file->get('filename')->getString() . ' a bien été sauvegardé (' . $formated_filesize . ').');
}
